name: webviewimage
description: A Flutter plugin that provides a WebView widget to image_network.
version: 0.0.5
homepage: https://github.com/gabrielpatricksouza/webviewimage
publish_to: "none"

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  path: ^1.8.3
  pointer_interceptor: ^0.10.1
  uuid: ^3.0.7
  webview_flutter: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides: 
  web: ^0.4.2

flutter: